name: walkdown_app
description: Wind Turbine Walkdown App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+1
  path: ^1.9.0
  image: ^4.1.3
  pdf: ^3.10.4
  path_provider: ^2.1.1
  translator: ^1.0.0
  http: ^1.1.0
  file_picker: ^8.0.0
  share_plus: ^10.0.1
  media_scanner: ^2.2.0
  open_filex: ^4.5.0
  desktop_drop: ^0.4.0  # ou a última versão
  intl: 0.20.2
  image_picker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/logo_2ws.png
    - assets/1logo_2ws.png
    - lib/l10n/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf